image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "bnb-bank-api:latest"
  DOCKER_REGISTRY: "registry.gitlab.com/colmeia/bnb-bank"

build_image:
  stage: build
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - docker info
    - docker --version
    - cat "$ENV" > .env
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME .
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME
  only:
    - main

deploy:
  stage: deploy
  script:
    - apk update
    - apk add openssh-client
    - "which ssh-agent || ( apk add openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_host
    - ssh $SSH_USER@$SERVER_IP '
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker pull $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME &&
      docker run -d --name $DOCKER_IMAGE_NAME -p 0.0.0.0:80:80 $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME'

  only:
    - main
