version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "laravel"
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data:
